# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target '365KEY_swift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 365KEY_swift
pod "AFNetworking"
pod "SDWebImage"
pod "YYModel"
pod "FMDB"
pod "pop"
pod "SVProgressHUD"

end
