# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target '365KEY_swift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 365KEY_swift
pod "AFNetworking"
pod "SDWebImage"
pod "YYModel"
pod "FMDB"
pod "pop"
pod "SVProgressHUD"

# U-Share SDK UI模块（分享面板，建议添加）
pod ‘UMengUShare/UI’
# 集成新浪微博
pod ‘UMengUShare/Social/Sina'
# 集成微信
pod ‘UMengUShare/Social/WeChat'
# 集成QQ
pod ‘UMengUShare/Social/QQ'

end
